/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicProxyPageSplatRouteImport } from './routes/api/public/proxy/page.$'
import { Route as ApiPublicProxyAssetSplatRouteImport } from './routes/api/public/proxy/asset.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyPageSplatRoute = ApiPublicProxyPageSplatRouteImport.update({
  id: '/api/public/proxy/page/$',
  path: '/api/public/proxy/page/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyAssetSplatRoute =
  ApiPublicProxyAssetSplatRouteImport.update({
    id: '/api/public/proxy/asset/$',
    path: '/api/public/proxy/asset/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/proxy/asset/$': typeof ApiPublicProxyAssetSplatRoute
  '/api/public/proxy/page/$': typeof ApiPublicProxyPageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/proxy/asset/$': typeof ApiPublicProxyAssetSplatRoute
  '/api/public/proxy/page/$': typeof ApiPublicProxyPageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/proxy/asset/$': typeof ApiPublicProxyAssetSplatRoute
  '/api/public/proxy/page/$': typeof ApiPublicProxyPageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/proxy/asset/$' | '/api/public/proxy/page/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/proxy/asset/$' | '/api/public/proxy/page/$'
  id:
    | '__root__'
    | '/'
    | '/api/public/proxy/asset/$'
    | '/api/public/proxy/page/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicProxyAssetSplatRoute: typeof ApiPublicProxyAssetSplatRoute
  ApiPublicProxyPageSplatRoute: typeof ApiPublicProxyPageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy/page/$': {
      id: '/api/public/proxy/page/$'
      path: '/api/public/proxy/page/$'
      fullPath: '/api/public/proxy/page/$'
      preLoaderRoute: typeof ApiPublicProxyPageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy/asset/$': {
      id: '/api/public/proxy/asset/$'
      path: '/api/public/proxy/asset/$'
      fullPath: '/api/public/proxy/asset/$'
      preLoaderRoute: typeof ApiPublicProxyAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicProxyAssetSplatRoute: ApiPublicProxyAssetSplatRoute,
  ApiPublicProxyPageSplatRoute: ApiPublicProxyPageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
